// ============================================
// BUG REPORTER CONFIGURATION
// Generated by @viacoremedia/bug-reporter setup
// ============================================

export const SYSTEM_NAME = "Source One";
export const BUG_REPORTER_API_URL = "https://bug-reporter-tau.vercel.app";
