/**
 * Column definitions for the dealer performance table.
 * Columns with hasData: false are stubbed for future data sources.
 */

import type { TableColumn } from '../../types';

export const TABLE_COLUMNS: TableColumn[] = [
  {
    key: 'name',
    label: 'Dealer',
    align: 'left',
    width: '200px',
    minWidth: '160px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'locationCount',
    label: 'Locs',
    align: 'center',
    width: '40px',
    sortable: true,
    hasData: true,
    groupOnly: true,
  },
  {
    key: 'activityStatus',
    label: 'Status',
    align: 'center',
    width: '60px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'daysSinceLastApplication',
    label: 'Days Since App',
    shortLabel: 'DS App',
    align: 'right',
    width: '90px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'daysSinceLastApproval',
    label: 'Days Since Appr',
    shortLabel: 'DS Appr',
    align: 'right',
    width: '90px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'daysSinceLastBooking',
    label: 'Days Since Bkd',
    shortLabel: 'DS Bkd',
    align: 'right',
    width: '90px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'commDays',
    label: 'Contact',
    shortLabel: 'Contact',
    align: 'right',
    width: '80px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'visitToApp',
    label: 'Visit Resp',
    shortLabel: 'V Resp',
    align: 'right',
    width: '80px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'apps',
    label: 'Apps',
    align: 'right',
    width: '65px',
    sortable: true,
    hasData: false,
  },
  {
    key: 'approvals',
    label: 'Appr',
    align: 'right',
    width: '65px',
    sortable: true,
    hasData: false,
  },
  {
    key: 'declines',
    label: 'Decl',
    align: 'right',
    width: '65px',
    sortable: true,
    hasData: false,
  },
  {
    key: 'inHouse',
    label: 'In-H',
    align: 'right',
    width: '65px',
    sortable: true,
    hasData: false,
  },
  {
    key: 'booked',
    label: 'Bkd',
    align: 'right',
    width: '65px',
    sortable: true,
    hasData: false,
  },
  {
    key: 'bookedDollars',
    label: 'Booked $',
    align: 'right',
    width: '90px',
    sortable: true,
    hasData: false,
  },
  {
    key: 'lookToBook',
    label: 'L-B%',
    align: 'right',
    width: '65px',
    sortable: true,
    hasData: false,
  },
  {
    key: 'approvalToBook',
    label: 'A-B%',
    align: 'right',
    width: '65px',
    sortable: true,
    hasData: false,
  },
];
