/**
 * Column definitions for the dealer performance table.
 * Columns with hasData: false are stubbed for future data sources.
 */

import type { TableColumn } from '../../types';

export const TABLE_COLUMNS: TableColumn[] = [
  {
    key: 'name',
    label: 'Dealer',
    align: 'left',
    width: '240px',
    minWidth: '200px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'rep',
    label: 'Rep',
    align: 'left',
    width: '80px',
    sortable: false,
    hasData: true,
    dealerOnly: true,
  },
  {
    key: 'locationCount',
    label: 'Locs',
    align: 'center',
    width: '40px',
    sortable: true,
    hasData: true,
    groupOnly: true,
  },
  {
    key: 'activityStatus',
    label: 'Status',
    align: 'center',
    width: '60px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'daysSinceLastApplication',
    label: 'Days Since App',
    shortLabel: 'DS App',
    align: 'right',
    width: '90px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'daysSinceLastApproval',
    label: 'Days Since Appr',
    shortLabel: 'DS Appr',
    align: 'right',
    width: '90px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'daysSinceLastBooking',
    label: 'Days Since Bkd',
    shortLabel: 'DS Bkd',
    align: 'right',
    width: '90px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'commDays',
    label: 'Contact',
    shortLabel: 'Contact',
    align: 'right',
    width: '80px',
    sortable: true,
    hasData: false,
  },
  {
    key: 'visitToApp',
    label: 'Visit Resp',
    shortLabel: 'V Resp',
    align: 'right',
    width: '80px',
    sortable: true,
    hasData: false,
  },
  {
    key: 'apps',
    label: 'Apps',
    align: 'right',
    width: '65px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'approvals',
    label: 'Appr',
    align: 'right',
    width: '65px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'inHouse',
    label: 'In-H',
    align: 'right',
    width: '65px',
    sortable: true,
    hasData: false, // Hidden — in-house tracking data not currently available
  },
  {
    key: 'leadBooked',
    label: 'App BKD',
    description: 'App Booked: Number of deals booked originating specifically from applications submitted in this period (Cohort Model).',
    align: 'right',
    width: '65px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'leadBookedDollars',
    label: 'App $',
    description: 'App Booked Volume: Dollar volume booked originating specifically from applications submitted in this period (Cohort Model).',
    align: 'right',
    width: '85px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'booked',
    label: 'Funded BKD',
    description: 'Funded Deals: Total deals funded/closed in this period regardless of application date (Cash Production Model).',
    align: 'right',
    width: '65px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'bookedDollars',
    label: 'Funded $',
    description: 'Funded Volume: Total dollar volume funded/closed in this period regardless of application date (Cash Production Model).',
    align: 'right',
    width: '90px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'lookToBook',
    label: 'L-B%',
    description: 'Look-to-Book %: Total booked from applications in period / Total applications in period. (Note: Requires ~30d seasoning for full cohort maturity).',
    align: 'right',
    width: '65px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'approvalToBook',
    label: 'A-B%',
    description: 'Approval-to-Book %: Total booked from applications in period / Total approved in period. Measures dealer closing pull-through without underwriting bias (allows ~30d lag for seasoning).',
    align: 'right',
    width: '65px',
    sortable: true,
    hasData: true,
  },
  {
    key: 'avgFico',
    label: 'AVG FICO',
    description: 'Average FICO score across applications received in this period.',
    align: 'right',
    width: '70px',
    sortable: true,
    hasData: true,
  },
];
